# Use the official JDK 22 runtime as a parent image
FROM openjdk:22-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file to the container
COPY target/useractivityservice-0.0.1-SNAPSHOT.jar useractivityservice.jar

# Expose port 8084 for the container
EXPOSE 8084

# Run the application
ENTRYPOINT ["java", "-jar", "useractivityservice.jar"]
