# Use the official JDK 22 runtime as a parent image
FROM openjdk:22-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file to the container
COPY target/reviewservice-0.0.1-SNAPSHOT.jar reviewservice.jar

# Expose port 8083 for the container
EXPOSE 8083

# Run the application
ENTRYPOINT ["java", "-jar", "reviewservice.jar"]
