# Use the official JDK 22 runtime as a parent image
FROM openjdk:22-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file to the container
COPY target/userservice-0.0.1-SNAPSHOT.jar userservice.jar

# Expose port 8082 for the container
EXPOSE 8082

# Run the application
ENTRYPOINT ["java", "-jar", "userservice.jar"]
